# Generated by Django 3.1.1 on 2021-02-15 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name', models.CharField(max_length=20, verbose_name="Doctor's first name")),
                ('last_name', models.CharField(max_length=20, verbose_name="Doctor's last name")),
                ('phone', models.PositiveIntegerField()),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(blank=True, max_length=15, null=True)),
                ('mail', models.EmailField(max_length=254, verbose_name='email')),
                ('date_entry', models.DateField(blank=True, null=True, verbose_name='date entry')),
                ('date_out', models.DateField(blank=True, null=True, verbose_name='date entry')),
            ],
            options={
                'ordering': ['frist_name'],
            },
        ),
        migrations.CreateModel(
            name='Sanad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_date', models.DateField(auto_now_add=True, verbose_name='date entry')),
                ('values', models.CharField(max_length=10)),
                ('note', models.CharField(blank=True, max_length=300, null=True, verbose_name='note')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanads', to='mainpage.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Secertary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mail', models.EmailField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=40, null=True)),
                ('active', models.BooleanField(default=False)),
                ('other', models.TextField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=8, null=True)),
                ('dateEntry', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section_of_Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('position', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name', models.CharField(max_length=20, verbose_name="Sick's first name")),
                ('mid_name', models.CharField(blank=True, max_length=20, verbose_name="Sick's middle name")),
                ('last_name', models.CharField(max_length=20, verbose_name="Sick's last name")),
                ('mail', models.EmailField(max_length=254, verbose_name='email')),
                ('old', models.CharField(blank=True, max_length=20, verbose_name='old')),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('none', 'none')], default='none', max_length=10)),
                ('blood', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('none', 'null')], default='none', max_length=5, verbose_name='blood')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='note')),
                ('sanads', models.ManyToManyField(through='mainpage.Sanad', to='mainpage.Doctor')),
            ],
        ),
        migrations.AddField(
            model_name='sanad',
            name='sick',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.sick'),
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.TimeField(verbose_name='time period start')),
                ('time_to', models.TimeField(verbose_name='time period end')),
                ('doctor', models.ManyToManyField(to='mainpage.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.PositiveIntegerField(unique=True, verbose_name='number of month')),
                ('days', models.DateField(unique=True)),
                ('period', models.ManyToManyField(to='mainpage.Period')),
            ],
        ),
    ]
