# Generated by Django 3.1.3 on 2021-01-09 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_month_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_date', models.DateField(auto_now_add=True, verbose_name='date entry')),
                ('values', models.CharField(max_length=10)),
                ('note', models.CharField(blank=True, max_length=300, null=True, verbose_name='note')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Section_of_Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('position', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name', models.CharField(max_length=20, verbose_name="Sick's first name")),
                ('mid_name', models.CharField(blank=True, max_length=20, verbose_name="Sick's middle name")),
                ('last_name', models.CharField(max_length=20, verbose_name="Sick's last name")),
                ('mail', models.EmailField(max_length=254, verbose_name='email')),
                ('old', models.CharField(blank=True, max_length=20, verbose_name='old')),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('none', 'none')], default='none', max_length=10)),
                ('blood', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('none', 'null')], default='none', max_length=5, verbose_name='blood')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='note')),
                ('sanads', models.ManyToManyField(through='mainpage.Sanad', to='mainpage.Doctor')),
            ],
        ),
        migrations.AddField(
            model_name='sanad',
            name='sick',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.sick'),
        ),
    ]
