# Generated by Django 3.1.1 on 2021-02-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20210109_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secertary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mail', models.EmailField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=40, null=True)),
                ('active', models.BooleanField(default=False)),
                ('other', models.TextField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=8, null=True)),
                ('dateEntry', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['frist_name']},
        ),
    ]
