# Generated by Django 3.1.1 on 2021-02-12 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20210211_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanad',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanads', to='mainpage.doctor'),
        ),
    ]
