# Generated by Django 3.1.1 on 2021-04-01 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COURSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TEACHER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_Code', models.CharField(max_length=100)),
                ('FN', models.CharField(max_length=100)),
                ('LN', models.CharField(max_length=100)),
                ('Dept_Code', models.CharField(max_length=100)),
                ('Ext', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SUBJECT',
            fields=[
                ('Subject_Code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Subject_Name', models.CharField(max_length=100)),
                ('T_Code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Note_Test.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='COURSE_SUBJECT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_Type', models.CharField(max_length=100)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Note_Test.course')),
                ('Subject_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Note_Test.subject')),
            ],
        ),
    ]
