# Generated by Django 3.1.1 on 2021-02-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name', models.CharField(max_length=20, verbose_name="Doctor's first name")),
                ('last_name', models.CharField(max_length=20, verbose_name="Doctor's last name")),
                ('phone', models.PositiveIntegerField()),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(blank=True, max_length=15, null=True)),
                ('mail', models.EmailField(max_length=254, verbose_name='email')),
                ('date_entry', models.DateField(blank=True, null=True, verbose_name='date entry')),
                ('date_out', models.DateField(blank=True, null=True, verbose_name='date entry')),
            ],
        ),
    ]
